# Generated by Django 4.1.7 on 2023-04-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnosis'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
