# Generated by Django 4.1.7 on 2023-04-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_appointment_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
