# Generated by Django 4.1.7 on 2023-04-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_category_doctorprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
